services:
  db:
    image: postgres:16.10
    container_name: handoff-postgres
    environment:
      POSTGRES_DB: handoff
      POSTGRES_USER: handoff
      POSTGRES_PASSWORD: handoff
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    container_name: handoff-backend
    environment:
      SPRING_PROFILES_ACTIVE: local
      # JDBC connection for local profile
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: handoff
      DB_USERNAME: handoff
      DB_PASSWORD: handoff
      # Redis connection for the local profile
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # JWT defaults
      JWT_SECRET: /aRsK12WN9h4RS0rvhmI/WbDaWWTadfJbvKLCmUNVV4=
      JWT_EXPIRATION: 86400000
      # CORS for local frontend
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      # SMTP for local profile
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: 0d618da6d6ee0e
      MAIL_PASSWORD: 719eb3b06c7a23
    ports:
      - "8080:8080"
      - "5005:5005"   # Add this line for debug port
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: handoff-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
