spring:
  application:
    name: handoff-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# JWT defaults
jwt:
  secret: ${JWT_SECRET:change-this-secret-please}
  expiration: ${JWT_EXPIRATION:86400000}

# CORS defaults
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: "*"

# Actuator minimal exposure
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging
logging:
  level:
    com.handoff: INFO
    org.springframework.security: INFO

