spring:
  application:
    name: handoff-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# JWT defaults
jwt:
  secret: ${JWT_SECRET:change-this-secret-please}
  expiration: ${JWT_EXPIRATION:86400000}

# CORS defaults
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: "*"

# Actuator minimal exposure
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging
logging:
  level:
    com.handoff: INFO
    org.springframework.security: INFO

# Server
server:
  port: 8080
  servlet:
    context-path: /api/v1

---
# Local profile: in-memory H2 with JPA
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:handoff;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_ON_ERROR=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS handoff;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG

---
# Nonprod profile: PostgreSQL with JPA
spring:
  config:
    activate:
      on-profile: nonprod
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:handoff}}
    username: ${DB_USERNAME:handoff}
    password: ${DB_PASSWORD:handoff}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      minimum-idle: ${DB_POOL_MIN:2}
      connection-timeout: ${DB_CONN_TIMEOUT_MS:30000}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true

---
# Prod profile: PostgreSQL with JPA
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:4}
      connection-timeout: ${DB_CONN_TIMEOUT_MS:30000}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true

logging:
  level:
    com.handoff: INFO
    org.springframework.security: WARN
