server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:handoff;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Disable Flyway in dev unless migrations are added
spring.flyway.enabled: false

